### ISSUE TITLE
 ./manage.py cities_light  --force-all not work give me TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by developermasrawy** [yourlabs/django-cities-light#138]
./manage.py cities_light  --force-all
RAM used: 44816 kB Time: 0:00:03 Done: 100%|#################################################################################################################|
RAM used: 45092 kB Time: 0:02:27 Done: 100%|#################################################################################################################|
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/TrustNoBody/django-env/ischool/lib64/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/TrustNoBody/django-env/ischool/lib64/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/TrustNoBody/django-env/ischool/lib64/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/TrustNoBody/django-env/ischool/lib64/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/TrustNoBody/django-env/ischool/lib64/python3.5/site-packages/cities_light/management/commands/cities_light.py", line 135, in handle
    geonames = Geonames(url, force=force)
  File "/home/TrustNoBody/django-env/ischool/lib64/python3.5/site-packages/cities_light/geonames.py", line 26, in __init__
    force=force
  File "/home/TrustNoBody/django-env/ischool/lib64/python3.5/site-packages/cities_light/geonames.py", line 48, in download
    force=force
  File "/home/TrustNoBody/django-env/ischool/lib64/python3.5/site-packages/cities_light/downloader.py", line 32, in download
    if not self.needs_downloading(source, destination, force):
  File "/home/TrustNoBody/django-env/ischool/lib64/python3.5/site-packages/cities_light/downloader.py", line 60, in needs_downloading
    src_size = int(src_file.headers['content-length'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by max-arnold** [comment]
Can't reproduce this. Could you provide additional details like python/django/cities-light versions? Also it would be nice if you add this print statement and post its output too:

```
        src_file = urlopen(source)
        print "%s\n%s\n%s" % (src_file.geturl(), src_file.getcode(), src_file.headers)
        src_size = int(src_file.headers['content-length'])
```
