### ISSUE TITLE
Data Import: Bad Zip File

### ISSUE THREAD

**Issue by nsomaru** [yourlabs/django-cities-light#140]
Got the following trace when trying to do `./manage.py cities_light` or `./manage.py cities_light --force-all`
```python
Traceback (most recent call last):
  File "./manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nikhil/.virtualenvs/ypo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/nikhil/.virtualenvs/ypo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nikhil/.virtualenvs/ypo/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nikhil/.virtualenvs/ypo/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/nikhil/.virtualenvs/ypo/local/lib/python2.7/site-packages/cities_light/management/commands/cities_light.py", line 135, in handle
    geonames = Geonames(url, force=force)
  File "/home/nikhil/.virtualenvs/ypo/local/lib/python2.7/site-packages/cities_light/geonames.py", line 38, in __init__
    self.extract(self.file_path, destination_file_name)
  File "/home/nikhil/.virtualenvs/ypo/local/lib/python2.7/site-packages/cities_light/geonames.py", line 57, in extract
    zip_file = zipfile.ZipFile(zip_path)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```
Not really sure what's going on. Perhaps geonames is no longer serving a zipfile?

**Comment by max-arnold** [comment]
Run `./manage.py shell` and then the following statements in django shell:

```
from cities_light import settings; print settings.DATA_DIR; print settings.SOURCES
```

Then inspect source files in DATA_DIR and try to unpack them manually.  In my case the output is:

```
/Users/max/repos/django-cities-light/cities_light/data
[u'http://download.geonames.org/export/dump/countryInfo.txt', u'http://download.geonames.org/export/dump/admin1CodesASCII.txt', u'http://download.geonames.org/export/dump/cities15000.zip', u'http://download.geonames.org/export/dump/alternateNames.zip']
```

and all files unpacked just fine.

**Comment by nsomaru** [comment]
I specified a language in my settings, and then it all worked out fine. Closing.
