### ISSUE TITLE
Tox failures on django-1.11/djangodev

### ISSUE THREAD

**Issue by max-arnold** [yourlabs/django-cities-light#143]
Just ran tox locally and got lots of failures:

```
  py27-django18-sqlite: commands succeeded
  py27-django18-mysql: commands succeeded
  py27-django18-postgresql: commands succeeded
  py27-django19-sqlite: commands succeeded
  py27-django19-mysql: commands succeeded
  py27-django19-postgresql: commands succeeded
  py27-django110-sqlite: commands succeeded
  py27-django110-mysql: commands succeeded
  py27-django110-postgresql: commands succeeded
ERROR:   py27-django11-sqlite: commands failed
ERROR:   py27-django11-mysql: commands failed
ERROR:   py27-django11-postgresql: commands failed
ERROR:   py27-djangodev-sqlite: could not install deps [pytest, pytest-django, pytest-cov, mock, coverage, django-dbdiff>=0.4.0, git+https://github.com/jpic/django-autoslug.git@dj20#egg=django-autoslug, https://github.com/django/django/archive/master.tar.gz]; v = InvocationError('/Users/user/play/django-cities-light/.tox/py27-djangodev-sqlite/bin/pip install pytest pytest-django pytest-cov mock coverage django-dbdiff>=0.4.0 git+https://github.com/jpic/django-autoslug.git@dj20#egg=django-autoslug https://github.com/django/django/archive/master.tar.gz (see /Users/user/play/django-cities-light/.tox/py27-djangodev-sqlite/log/py27-djangodev-sqlite-1.log)', 1)
ERROR:   py27-djangodev-mysql: could not install deps [pytest, pytest-django, pytest-cov, mock, coverage, django-dbdiff>=0.4.0, git+https://github.com/jpic/django-autoslug.git@dj20#egg=django-autoslug, https://github.com/django/django/archive/master.tar.gz, mysqlclient]; v = InvocationError('/Users/user/play/django-cities-light/.tox/py27-djangodev-mysql/bin/pip install pytest pytest-django pytest-cov mock coverage django-dbdiff>=0.4.0 git+https://github.com/jpic/django-autoslug.git@dj20#egg=django-autoslug https://github.com/django/django/archive/master.tar.gz mysqlclient (see /Users/user/play/django-cities-light/.tox/py27-djangodev-mysql/log/py27-djangodev-mysql-1.log)', 1)
ERROR:   py27-djangodev-postgresql: could not install deps [pytest, pytest-django, pytest-cov, mock, coverage, django-dbdiff>=0.4.0, git+https://github.com/jpic/django-autoslug.git@dj20#egg=django-autoslug, https://github.com/django/django/archive/master.tar.gz, psycopg2]; v = InvocationError('/Users/user/play/django-cities-light/.tox/py27-djangodev-postgresql/bin/pip install pytest pytest-django pytest-cov mock coverage django-dbdiff>=0.4.0 git+https://github.com/jpic/django-autoslug.git@dj20#egg=django-autoslug https://github.com/django/django/archive/master.tar.gz psycopg2 (see /Users/user/play/django-cities-light/.tox/py27-djangodev-postgresql/log/py27-djangodev-postgresql-1.log)', 1)
  py35-django18-sqlite: commands succeeded
  py35-django18-mysql: commands succeeded
  py35-django18-postgresql: commands succeeded
  py35-django19-sqlite: commands succeeded
  py35-django19-mysql: commands succeeded
  py35-django19-postgresql: commands succeeded
  py35-django110-sqlite: commands succeeded
  py35-django110-mysql: commands succeeded
  py35-django110-postgresql: commands succeeded
ERROR:   py35-django11-sqlite: commands failed
ERROR:   py35-django11-mysql: commands failed
ERROR:   py35-django11-postgresql: commands failed
  py35-djangodev-sqlite: commands succeeded
  py35-djangodev-mysql: commands succeeded
  py35-djangodev-postgresql: commands succeeded
  py36-django18-sqlite: commands succeeded
  py36-django18-mysql: commands succeeded
  py36-django18-postgresql: commands succeeded
  py36-django19-sqlite: commands succeeded
  py36-django19-mysql: commands succeeded
  py36-django19-postgresql: commands succeeded
  py36-django110-sqlite: commands succeeded
  py36-django110-mysql: commands succeeded
  py36-django110-postgresql: commands succeeded
ERROR:   py36-django11-sqlite: commands failed
ERROR:   py36-django11-mysql: commands failed
ERROR:   py36-django11-postgresql: commands failed
  py36-djangodev-sqlite: commands succeeded
  py36-djangodev-mysql: commands succeeded
  py36-djangodev-postgresql: commands succeeded
```

djangodev tests fail on py27 with the following error:

```
Collecting https://github.com/django/django/archive/master.tar.gz
  Downloading https://github.com/django/django/archive/master.tar.gz (7.7MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/y4/mx8yb7kd1gl26frnh7014dvm0000gp/T/pip-c59Jun-build/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 59, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'
```

django11 tests have something different:

```
  File "/Users/user/play/django-cities-light/.tox/py36-django11-postgresql/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/Users/user/play/django-cities-light/.tox/py36-django11-postgresql/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/Users/user/play/django-cities-light/.tox/py36-django11-postgresql/lib/python3.6/site-packages/pytest_django/plugin.py", line 241, in pytest_load_initial_conftests
    from django.conf import settings as dj_settings
ModuleNotFoundError: No module named 'django'
ERROR: InvocationError: '/Users/user/play/django-cities-light/.tox/py36-django11-postgresql/bin/py.test --cov cities_light --create-db --strict -r fEsxXw cities_light'
```

First failure can be fixed by running djangodev tests only on python=>3.5 (tox.ini), because Django 2.0 dropped support for python 2.7:

```
envlist = py{27,35,36}-django{18,19,110,11}{-sqlite,-mysql,-postgresql},py{35,36}-djangodev{-sqlite,-mysql,-postgresql}
```

Second failure is due to `11` in tox envlist. Should be 111. So the final proposed fix is:

```
envlist = py{27,35,36}-django{18,19,110,111}{-sqlite,-mysql,-postgresql},py{35,36}-djangodev{-sqlite,-mysql,-postgresql}
```

**Comment by max-arnold** [comment]
Also .travis.yml misses lots of combinations listed above

**Comment by max-arnold** [comment]
@jpic I'll add the fix to stable/3.x.x branch if there are no objections

**Comment by max-arnold** [comment]
Done :)

**Comment by max-arnold** [comment]
@jpic 
P.S. What is the policy for master branch? Should we base any pull requests on master, and then merge master into stable (release)?

**Comment by jpic** [comment]
I thought we dropped stable/3.x.x in favor of master on this repo xD

**Comment by max-arnold** [comment]
@jpic I merged my commits from stable/3.x.x to master (see here https://github.com/max-arnold/django-cities-light/commits/master), but can't push my master to upstream:

```
django-cities-light % git push yourlabs
Counting objects: 1, done.
Writing objects: 100% (1/1), 231 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci/push" is pending. At least one approved review is required
To github.com:yourlabs/django-cities-light.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:yourlabs/django-cities-light.git'
```

**Comment by jpic** [comment]
Can you disable branch protection in the settings temporarely ?

**Comment by max-arnold** [comment]
I have no access to repo settings on Github

**Comment by jpic** [comment]
You are now admin ;)​

**Comment by max-arnold** [comment]
Thanks!

I merged my fixes from stable/3.x.x to master (your Django 1.11/2.0 commits became duplicated, but git was smart enough). From now on I'll try to base all my features on master.
