### ISSUE TITLE
python manage.py cities_light giving zipfile.BadZipfile error

### ISSUE THREAD

**Issue by mansimarkaur** [yourlabs/django-cities-light#162]
`python manage.py cities_light` gives the following error: 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Library/Python/2.7/site-packages/cities_light/management/commands/cities_light.py", line 137, in handle
    geonames = Geonames(url, force=force)
  File "/Library/Python/2.7/site-packages/cities_light/geonames.py", line 47, in __init__
    self.extract(self.file_path, destination_file_name)
  File "/Library/Python/2.7/site-packages/cities_light/geonames.py", line 83, in extract
    zip_file = zipfile.ZipFile(zip_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```
@jpic @max-arnold Could you please help? Thanks.

**Comment by jpic** [comment]
What happens after you remove the downloaded zip file from cities light data directory and try again ?
