### ISSUE TITLE
Bug into DB migration script

### ISSUE THREAD

**Issue by Guts** [yourlabs/django-cities-light#167]
Configuration:

* DB : SQLite
* Django 1.11.*
* django-cities-light 3.3.0

Impossible to finish the setup because of an error in DB migration script:

```py
(virtenv) PS C:\Users\$USER\Documents\GitHub\Perso\django_prj> python .\manage.py makemigrations
Traceback (most recent call last):
  File ".\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\$USER\Documents\GitHub\Perso\django_prj\virtenv\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\$USER\Documents\GitHub\Perso\django_prj\virtenv\lib\site-packages\django\core\management\__init__.py", line 338, in execute
    django.setup()
  File "C:\Users\$USER\Documents\GitHub\Perso\django_prj\virtenv\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\$USER\Documents\GitHub\Perso\django_prj\virtenv\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\$USER\Documents\GitHub\Perso\django_prj\virtenv\lib\site-packages\django\apps\config.py", line 94, in create
    module = import_module(entry)
  File "C:\Users\$USER\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\$USER\Documents\GitHub\Perso\django_prj\virtenv\lib\site-packages\cities_light\__init__.py", line 3, in <module>
    from .settings import *
  File "C:\Users\$USER\Documents\GitHub\Perso\django_prj\virtenv\lib\site-packages\cities_light\settings.py", line 142, in <module>
    if 'mysql' in database['ENGINE'].lower():
KeyError: 'ENGINE'
```

**Comment by Guts** [comment]
The issue comes from the use of [database options](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-OPTIONS) in my project settings and more specifically of the [timeout delay for SQLite](https://docs.djangoproject.com/en/dev/ref/databases/#database-is-locked-errors).

In that case, the databases list returned is (note the second element):

```py
{'ENGINE': 'django.db.backends.sqlite3', 'NAME': 'C:\\Users\\$USER\\Documents\\GitHub\\Perso\\django_prj\\django_prj.sqlite'}
{'timeout': 30}
```

Furthermore, the use of `dict[key]` is not recommended to ensure access to a dict value (see [this SO conversation](https://stackoverflow.com/questions/11041405/why-dict-getkey-instead-of-dictkey)).

I managed this with a quick workaround:

```py
for database in list(settings.DATABASES.values()):
    if "ENGINE" in database.keys() and 'mysql' in database.get('ENGINE').lower():
        INDEX_SEARCH_NAMES = False
```

I'll submit a PR for this but i'm not sure that's a definitive solution.

**Comment by max-arnold** [comment]
Could you please show the value of your `DATABASES` dict from settings.py?

**Comment by max-arnold** [comment]
So far it looks like you have wrong nesting level for `OPTIONS`.

It should look like this (`OPTIONS` are per database, not global):

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'C:\\Users\\$USER\\Documents\\GitHub\\Perso\\django_prj\\django_prj.sqlite',
        'OPTIONS': {
            'timeout': 30
        }
    }
}
```

**Comment by Guts** [comment]
Oh, you're right, sorry!
I close this issue. I let you manage the PR.
