### ISSUE TITLE
python manage.py cities_light -> urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Legotckoi** [yourlabs/django-cities-light#200]
Hello, 

today I have got the following issue, when I executed the following command

python manage.py cities_light

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dekadent/evileg_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/dekadent/evileg_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dekadent/evileg_env/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dekadent/evileg_env/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/dekadent/evileg_env/lib/python3.6/site-packages/cities_light/management/commands/cities_light.py", line 171, in handle
    geonames = Geonames(url, force=force)
  File "/Users/dekadent/evileg_env/lib/python3.6/site-packages/cities_light/geonames.py", line 27, in __init__
    force=force
  File "/Users/dekadent/evileg_env/lib/python3.6/site-packages/cities_light/geonames.py", line 50, in download
    force=force
  File "/Users/dekadent/evileg_env/lib/python3.6/site-packages/cities_light/downloader.py", line 35, in download
    if not self.needs_downloading(source, destination, force):
  File "/Users/dekadent/evileg_env/lib/python3.6/site-packages/cities_light/downloader.py", line 64, in needs_downloading
    src_file = urlopen(source)
  File "/Users/dekadent/.pyenv/versions/3.6.7/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/dekadent/.pyenv/versions/3.6.7/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Users/dekadent/.pyenv/versions/3.6.7/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/dekadent/.pyenv/versions/3.6.7/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Users/dekadent/.pyenv/versions/3.6.7/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/dekadent/.pyenv/versions/3.6.7/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

In morning all was okay, but in evening I have this issue. I checked it from two PC. 
I think it can be issue with changes in urls in geonames.

**Comment by max-arnold** [comment]
Just did a quick test, and everything works as expected. All the URLs are also fine, you can try them in your browser:

```
COUNTRY_SOURCES = getattr(settings, 'CITIES_LIGHT_COUNTRY_SOURCES',
    ['http://download.geonames.org/export/dump/countryInfo.txt'])
REGION_SOURCES = getattr(settings, 'CITIES_LIGHT_REGION_SOURCES',
    ['http://download.geonames.org/export/dump/admin1CodesASCII.txt'])
CITY_SOURCES = getattr(settings, 'CITIES_LIGHT_CITY_SOURCES',
    ['http://download.geonames.org/export/dump/cities15000.zip'])
TRANSLATION_SOURCES = getattr(settings, 'CITIES_LIGHT_TRANSLATION_SOURCES',
    ['http://download.geonames.org/export/dump/alternateNames.zip'])
```

**Comment by Legotckoi** [comment]
> Just did a quick test, and everything works as expected. All the URLs are also fine, you can try them in your browser:
> 
> ```
> COUNTRY_SOURCES = getattr(settings, 'CITIES_LIGHT_COUNTRY_SOURCES',
>     ['http://download.geonames.org/export/dump/countryInfo.txt'])
> REGION_SOURCES = getattr(settings, 'CITIES_LIGHT_REGION_SOURCES',
>     ['http://download.geonames.org/export/dump/admin1CodesASCII.txt'])
> CITY_SOURCES = getattr(settings, 'CITIES_LIGHT_CITY_SOURCES',
>     ['http://download.geonames.org/export/dump/cities15000.zip'])
> TRANSLATION_SOURCES = getattr(settings, 'CITIES_LIGHT_TRANSLATION_SOURCES',
>     ['http://download.geonames.org/export/dump/alternateNames.zip'])
> ```

Hello, 
Probably it is my local issue with internet connection from home. I tried from work, and yes - you are right - It works as expected. In evening I will check from home one more. But, I close this issue. 

Thank you for answer, I also check you suggestion, and will a results. In minimal - it will be useful in similar situations for another developers.

**Comment by NaturalBornCamper** [comment]
Hello, I think I figured out the issue, it might be when geonames is doing its daily dump, as it's half past midnight in EST timezone now and this is available:

- http://download.geonames.org/export/dump/countryInfo.txt

And these show a 404 page in the browser:

- http://download.geonames.org/export/dump/admin1CodesASCII.txt
- http://download.geonames.org/export/dump/cities15000.zip
- http://download.geonames.org/export/dump/alternateNames.zip

It's not a quota issue as I've also tried on my cellphone using data (different IP)

![image](https://user-images.githubusercontent.com/1697306/96540925-e56fa800-126c-11eb-94c6-730c853d62b4.png)

**Comment by jatindergit** [comment]
I am facing this issue since morning.
