### ISSUE TITLE
LookupError: App '...' doesn't have a 'SubRegion' model.

### ISSUE THREAD

**Issue by madhav-dhungana** [yourlabs/django-cities-light#260]
System check identified 8 issues (0 silenced).
E:\al-bahri\web\project1\bahri\bahri\settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\config.py", line 268, in get_model      
    return self.models[model_name.lower()]
KeyError: 'subregion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper    
    fn(*args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\core\management\commands\runserver.py", line 
110, in inner_run
    autoreload.raise_last_exception()
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "E:\al-bahri\web\project1\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper    
    fn(*args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\registry.py", line 122, in populate     
    app_config.ready()
  File "E:\al-bahri\web\project1\lib\site-packages\django\contrib\admin\apps.py", line 27, in ready    
    self.module.autodiscover()
  File "E:\al-bahri\web\project1\lib\site-packages\django\contrib\admin\__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\admin.py", line 7, in <module>
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\forms.py", line 5, in <module>
    Country, Region, SubRegion, City = get_cities_models()
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\loading.py", line 17, in get_cities_models
    return [get_cities_model(model_name) for model_name in model_names]
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\loading.py", line 17, in <listcomp>    
    return [get_cities_model(model_name) for model_name in model_names]
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\loading.py", line 12, in get_cities_model
    return get_model(CITIES_LIGHT_APP_NAME, model_name, *args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\registry.py", line 211, in get_model    
    return app_config.get_model(model_name, require_ready=require_ready)
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\config.py", line 270, in get_model      
    raise LookupError(
LookupError: App 'ecommerce' doesn't have a 'SubRegion' model.
(project1) PS E:\al-bahri\web\project1\bahri> python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\config.py", line 268, in get_model      
    return self.models[model_name.lower()]
KeyError: 'subregion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper    
    fn(*args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\core\management\commands\runserver.py", line 
110, in inner_run
    autoreload.raise_last_exception()
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "E:\al-bahri\web\project1\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper    
    fn(*args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\registry.py", line 122, in populate     
    app_config.ready()
  File "E:\al-bahri\web\project1\lib\site-packages\django\contrib\admin\apps.py", line 27, in ready    
    self.module.autodiscover()
  File "E:\al-bahri\web\project1\lib\site-packages\django\contrib\admin\__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\admin.py", line 7, in <module>
    from . import forms
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\forms.py", line 5, in <module>
    Country, Region, SubRegion, City = get_cities_models()
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\loading.py", line 17, in get_cities_models
    return [get_cities_model(model_name) for model_name in model_names]
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\loading.py", line 17, in <listcomp>    
    return [get_cities_model(model_name) for model_name in model_names]
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\loading.py", line 12, in get_cities_model
    return get_model(CITIES_LIGHT_APP_NAME, model_name, *args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\registry.py", line 211, in get_model    
    return app_config.get_model(model_name, require_ready=require_ready)
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\config.py", line 270, in get_model      
    raise LookupError(
LookupError: App 'ecommerce' doesn't have a 'SubRegion' model.
E:\al-bahri\web\project1\bahri\ecommerce\models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper    
    fn(*args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\core\management\commands\runserver.py", line 
110, in inner_run
    autoreload.raise_last_exception()
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "E:\al-bahri\web\project1\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper    
    fn(*args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\registry.py", line 114, in populate     
    app_config.import_models()
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\config.py", line 301, in import_models  
    self.models_module = import_module(models_module_name)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\al-bahri\web\project1\bahri\ecommerce\models.py", line 350, in <module>
    class SubRegion(AbstractSubRegion):
NameError: name 'AbstractSubRegion' is not defined
E:\al-bahri\web\project1\bahri\ecommerce\models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper    
    fn(*args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\core\management\commands\runserver.py", line 
110, in inner_run
    autoreload.raise_last_exception()
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "E:\al-bahri\web\project1\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper    
    fn(*args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\registry.py", line 114, in populate     
    app_config.import_models()
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\config.py", line 301, in import_models  
    self.models_module = import_module(models_module_name)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\al-bahri\web\project1\bahri\ecommerce\models.py", line 350, in <module>
    class SubRegion(SubRegion):
NameError: name 'SubRegion' is not defined
E:\al-bahri\web\project1\bahri\ecommerce\models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\config.py", line 268, in get_model      
    return self.models[model_name.lower()]
KeyError: 'subregion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper    
    fn(*args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\core\management\commands\runserver.py", line 
110, in inner_run
    autoreload.raise_last_exception()
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "E:\al-bahri\web\project1\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper    
    fn(*args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\registry.py", line 122, in populate     
    app_config.ready()
  File "E:\al-bahri\web\project1\lib\site-packages\django\contrib\admin\apps.py", line 27, in ready    
    self.module.autodiscover()
  File "E:\al-bahri\web\project1\lib\site-packages\django\contrib\admin\__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "E:\al-bahri\web\project1\lib\site-packages\django\utils\module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\admin.py", line 7, in <module>
    from . import forms
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\forms.py", line 5, in <module>
    Country, Region, SubRegion, City = get_cities_models()
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\loading.py", line 17, in get_cities_models
    return [get_cities_model(model_name) for model_name in model_names]
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\loading.py", line 17, in <listcomp>    
    return [get_cities_model(model_name) for model_name in model_names]
  File "E:\al-bahri\web\project1\lib\site-packages\cities_light\loading.py", line 12, in get_cities_model
    return get_model(CITIES_LIGHT_APP_NAME, model_name, *args, **kwargs)
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\registry.py", line 211, in get_model    
    return app_config.get_model(model_name, require_ready=require_ready)
  File "E:\al-bahri\web\project1\lib\site-packages\django\apps\config.py", line 270, in get_model      
    raise LookupError(
LookupError: App 'ecommerce' doesn't have a 'SubRegion' model.

**Comment by ton77v** [comment]
I had similar issue, fixed like this. In xx/models:

`from cities_light.abstract_models import (AbstractCountry, AbstractRegion,
                                          AbstractCity, AbstractSubRegion)

....            

class SubRegion(AbstractSubRegion):
    pass

connect_default_signals(SubRegion)                              
                                          
                                          `
