### ISSUE TITLE
can't find countryInfo.txt in http://download.geonames.org/export/dump/

### ISSUE THREAD

**Issue by a-benkhaled** [yourlabs/django-cities-light#265]
Hi 
when i run  `python manage.py cities_light --progress -v 3  --force-all --traceback`
I get this error stack

> Traceback (most recent call last):
>   File "manage.py", line 15, in <module>
>     execute_from_command_line(sys.argv)
>   File "/Users/mac/Documents/***/***/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
>     utility.execute()
>   File "/Users/mac/Documents/***/***/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 413, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/Users/mac/Documents/***/***/venv/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/Users/mac/Documents/***/***/venv/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
>     output = self.handle(*args, **options)
>   File "/Users/mac/Documents/***/***/venv/lib/python3.6/site-packages/cities_light/management/commands/cities_light.py", line 179, in handle
>     geonames = Geonames(url, force=force)
>   File "/Users/mac/Documents/***/***/venv/lib/python3.6/site-packages/cities_light/geonames.py", line 24, in __init__
>     force=force
>   File "/Users/mac/Documents/***/***/venv/lib/python3.6/site-packages/cities_light/geonames.py", line 48, in download
>     force=force
>   File "/Users/mac/Documents/***/***/venv/lib/python3.6/site-packages/cities_light/downloader.py", line 28, in download
>     if not self.needs_downloading(source, destination, force):
>   File "/Users/mac/Documents/***/***/venv/lib/python3.6/site-packages/cities_light/downloader.py", line 59, in needs_downloading
>     src_file = urlopen(source)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
>     response = meth(req, response)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
>     return self._call_chain(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found
> 

Then I tried to print the url in **cities_light.py**  I found that there is no **http://download.geonames.org/export/dump/countryInfo.txt**

am I missing something ? 
yesterday this cmd worked fine! I though maybe this file was accidentally removed from the server

**Comment by a-benkhaled** [comment]
FIXED 
thanx
