### ISSUE TITLE
Problems with encoding using MySQL

### ISSUE THREAD

**Issue by mauricioabreu** [yourlabs/django-cities-light#84]
Hey @jpic 

First, thanks for the work! :-)

I remember the last time I used django-cities-light everything was up and running here.

I use Centos 6.4 on production machines and it uses Python 2.6. Is Python 2.6 still supported?

I am having a hard time trying to load django-cities-light here. Follows the traceback:

```
/usr/local/venv/myenv/lib/python2.6/site-packages/zerorpc/events.py:31: DeprecationWarning: gevent.coros has been renamed to gevent.lock
  import gevent.coros
/usr/local/venv/myenv/lib/python2.6/site-packages/autoslug/utils.py:30: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.
  return django_slugify(unidecode(value))
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/cities_light/management/commands/cities_light.py", line 169, in handle
    self.country_import(items)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/cities_light/management/commands/cities_light.py", line 256, in country_import
    self.save(country)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/cities_light/management/commands/cities_light.py", line 495, in save
    model.save()
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/mysql/connector/django/base.py", line 133, in execute
    return self._execute_wrapper(self.cursor.execute, query, args)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/mysql/connector/django/base.py", line 116, in _execute_wrapper
    utils.ProgrammingError(err.msg), sys.exc_info()[2])
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/mysql/connector/django/base.py", line 113, in _execute_wrapper
    return method(query, args)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/mysql/connector/cursor.py", line 480, in execute
    stmt = operation % self._process_params(params)
  File "/usr/local/venv/myenv/lib/python2.6/site-packages/mysql/connector/cursor.py", line 355, in _process_params
    "Failed processing format-parameters; %s" % err)
django.db.utils.ProgrammingError: Failed processing format-parameters; Python 'safetext' cannot be converted to a MySQL type
```

I connected to my database and I checked the charset using the following command: SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'azionmanager02_hlg';

Result was:

DEFAULT_CHARACTER_SET_NAME : utf8  
DEFAULT_COLLATION_NAME : utf8_general_ci 

Am I missing something?

**Comment by st4lk** [comment]
Hi @mauricioabreu,
just in case, precise what version of django-cities-light are you using?

**Comment by mauricioabreu** [comment]
Really sorry! I forgot the version:

CentOS 6.4
Python 2.6 (system version)
MySQL 5.1.73 (Percona distribution)
django-cities-light 3.1.0

**Comment by mauricioabreu** [comment]
I am suspecting this is a MySQL problem. 
I think after creating the database, in some cases, there is no way back to set the charset to utf8.

**Comment by mauricioabreu** [comment]
Update: I created the database using utf8 and utf8-general-ci and I still get errors.

**Comment by mauricioabreu** [comment]
If we have the chance to support Python 2.6, can we add it to Travis CI?

**Comment by mauricioabreu** [comment]
I think I just discovered what is the problem.

Since the problem was pointing to autoslug (django-autoslug) it is an error that probably happens on Python 2.6 builds. :( I think I am going to provide a patch to django-autoslug soon.

**Comment by jpic** [comment]
Feel free to create a branch / PR with Python 2.6 support in travis.

**Comment by mauricioabreu** [comment]
but it is not a django-cities-light problem. 
Is it not better to provide a patch do django-autoslug instead of changing anything here? :)

Thanks for your support.

**Comment by hesamd** [comment]
I'm on python 2.7 and get a slug warning running the tests:
```
RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.
```
Also two of the unit tests do not pass.

**Comment by jpic** [comment]
Did you try the suggested fix ? (use another django-autoslug version).​

**Comment by hesamd** [comment]
I haven't. I assumed that since I'm using the latest django version (1.8.3) it comes with the latest version, isn't? Do you recommend down grading to an older version? There couple of other issues and warning which I probably open new issues for them or send a pull request.
