### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by gianrubio** [yourlabs/django-cities-light#90]
i 'm trying to run tests on django and there was a mistake with django cities light.
Always i use django test in my app it was sucessfully finished with no error. Last week i added cities light to my app and my test was broken.

I'm running django 1.8 and cities light 3.1.2
./manage.py test 
...

Synchronizing apps without migrations:
....

Running pre-migrate handlers for application autocomplete_light
Running pre-migrate handlers for application cities_light
.....
  Creating tables...
    Creating table thumbnail_kvstore
    Creating table log_logtype
    Creating table accounts_user
    Creating table corsheaders_corsmodel
    Creating table django_ses_sesstat
    Running deferred SQL...
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/test/runner.py", line 210, in run_tests
    old_config = self.setup_databases()
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/test/runner.py", line 166, in setup_databases
    **kwargs
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/test/runner.py", line 370, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 368, in create_test_db
    test_flush=True,
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 317, in sync_apps
    cursor.execute(statement)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/gianrubio/Virtualenvs/admag/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "cities_light_city" does not exist

**Comment by st4lk** [comment]
Hi Giancarlo.
Please precise, how you added cities light to your project?
You just add `'cities_light',` to your `INSTALLED_APPS`?
Our maybe you additionally set `CITIES_LIGHT_APP_NAME = 'your_app'` to use Abstract models?

**Comment by gianrubio** [comment]
Yes my cities light sare abstract, it's my mistake. I forgot to create the migrations.
Thank you
