### ISSUE TITLE
manage.py cities_light --force-all fails

### ISSUE THREAD

**Issue by duaneking** [yourlabs/django-cities-light#92]
So I'm attempting to start an entirely  new project starting from scratch with the newest everything in an attempt to get things working.. and cities-light fails to do its thing.

python -c "import django;print django.get_version()" gives 1.8.2
Django-cities-light is version 3.1.2

My command and output:

C:\Users\Duane\Dropbox\code\github\gpstrack>python manage.py cities_light --force-all -v 3

C:\Python27\lib\site-packages\south\modelsinspector.py:20: RemovedInDjango19Warning: djang
o.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its conten
ts have been moved to the fields, forms, and admin submodules of django.contrib.contenttyp
es.
  from django.contrib.contenttypes import generic

RAM used: ?? kB Time: 0:00:41 Done: 100%|#####################################|
No handlers could be found for logger "cities_light"                          |
RAM used: ?? kB Time: 0:12:40 Done: 100%|#####################################|
Traceback (most recent call last)::  18%|######                               |
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 338, in ex
ecute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 330, in ex
ecute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 390, in run_fr
om_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 441, in execut
e
    output = self.handle(*args, **options)
  File "C:\Python27\lib\site-packages\cities_light\management\commands\cities_light.py", l
ine 163, in handle
    self.city_import(items)
  File "C:\Python27\lib\site-packages\cities_light\management\commands\cities_light.py", l
ine 394, in city_import
    self.save(city)
  File "C:\Python27\lib\site-packages\cities_light\management\commands\cities_light.py", l
ine 501, in save
    model.save()
  File "C:\Python27\lib\site-packages\django\db\transaction.py", line 235, in __exit__
    connection.rollback()
  File "C:\Python27\lib\site-packages\django\db\backends\base\base.py", line 183, in rollb
ack
    self._rollback()
  File "C:\Python27\lib\site-packages\django\db\backends\base\base.py", line 147, in _roll
back
    return self.connection.rollback()
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\base\base.py", line 147, in _roll
back
    return self.connection.rollback()
django.db.utils.OperationalError: cannot rollback - no transaction is active

No matter what I do, following the documentation doesn't give me a working install. In fact the documentation for cities-light seems to be missing steps for the new migrations part of Django.

Am I doing something wrong?

**Comment by duaneking** [comment]
If I add the logging I mentioned in #93 and run the command just as I wrote about above I get the following output:

C:\Users\Duane\Dropbox\code\github\gpstrack>python manage.py cities_light --force-all -v 3

C:\Python27\lib\site-packages\south\modelsinspector.py:20: RemovedInDjango19Warning: djang
o.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its conten
ts have been moved to the fields, forms, and admin submodules of django.contrib.contenttyp
es.
  from django.contrib.contenttypes import generic

2015-06-21 22:35:13,796 - cities_light - INFO - Downloading http://download.geonames.org/e
xport/dump/countryInfo.txt into C:\Python27\lib\site-packages\cities_light\data\countryInf
o.txt
2015-06-21 22:35:14,167 - cities_light - INFO - Importing countryInfo.txt
RAM used: ?? kB Time: 0:00:37 Done: 100%|#####################################|
2015-06-21 22:35:52,167 - cities_light - INFO - Downloading http://download.geonames.org/e
xport/dump/admin1CodesASCII.txt into C:\Python27\lib\site-packages\cities_light\data\admin
1CodesASCII.txt
2015-06-21 22:35:53,822 - cities_light - INFO - Importing admin1CodesASCII.txt
2015-06-21 22:37:04,398 - cities_light - WARNING - Saving Minsk, Belarus failed: columns c
ountry_id, slug are not unique
2015-06-21 22:40:42,381 - cities_light - WARNING - Saving Vientiane, Laos failed: columns
country_id, slug are not unique
2015-06-21 22:41:05,480 - cities_light - WARNING - Saving Daugavpils, Latvia failed: colum
ns country_id, slug are not unique
2015-06-21 22:43:35,632 - cities_light - WARNING - Saving Ash Sharqiyah, Oman failed: colu
mns country_id, slug are not unique
2015-06-21 22:43:35,638 - cities_light - WARNING - Saving Al Batinah, Oman failed: columns
 country_id, slug are not unique
2015-06-21 22:43:41,107 - cities_light - WARNING - Saving Lima, Peru failed: columns count
ry_id, slug are not unique
RAM used: ?? kB Time: 0:12:27 Done: 100%|#####################################|
2015-06-21 22:48:21,569 - cities_light - INFO - Downloading http://download.geonames.org/e
xport/dump/cities15000.zip into C:\Python27\lib\site-packages\cities_light\data\cities1500
0.zip
2015-06-21 22:48:27,753 - cities_light - INFO - Importing cities15000.zip
Traceback (most recent call last)::   0%|                                     |
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 338, in ex
ecute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 330, in ex
ecute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 390, in run_fr
om_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 441, in execut
e
    output = self.handle(*args, **options)
  File "C:\Python27\lib\site-packages\cities_light\management\commands\cities_light.py", l
ine 169, in handle
    self.city_import(items)
  File "C:\Python27\lib\site-packages\cities_light\management\commands\cities_light.py", l
ine 400, in city_import
    self.save(city)
  File "C:\Python27\lib\site-packages\cities_light\management\commands\cities_light.py", l
ine 507, in save
    model.save()
  File "C:\Python27\lib\site-packages\django\db\transaction.py", line 235, in __exit__
    connection.rollback()
  File "C:\Python27\lib\site-packages\django\db\backends\base\base.py", line 183, in rollb
ack
    self._rollback()
  File "C:\Python27\lib\site-packages\django\db\backends\base\base.py", line 147, in _roll
back
    return self.connection.rollback()
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\base\base.py", line 147, in _roll
back
    return self.connection.rollback()
django.db.utils.OperationalError: cannot rollback - no transaction is active

**Comment by jpic** [comment]
I have nothing against windows support but i don't have any windows because it hates me so I'll merge patches for windows support as long as they don't break tests.

**Comment by jpic** [comment]
What Python and Database version BTW L

**Comment by duaneking** [comment]
Its python 2.7 as that is the only version supported on AWS.  

I'm not using postgresql on the command line atm, its all sqlite using the native django stuff.
