### ISSUE TITLE
Not able to populate database on live server. KeyError: u'last-modified'

### ISSUE THREAD

**Issue by pfremp** [yourlabs/django-cities-light#95]
Everything works fine on localhost, however when trying to populate the database via './manage.py cities_light' I get a KeyError: KeyError: u'last-modified'. 

I'm not too sure if there is something wrong with the server config that is preventing the cities data to be downloaded. See traceback below.

    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/pfremp/.virtualenvs/partfinder/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_co
    mmand_line
        utility.execute()
      File "/home/pfremp/.virtualenvs/partfinder/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/pfremp/.virtualenvs/partfinder/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/home/pfremp/.virtualenvs/partfinder/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
        output = self.handle(*args, **options)
      File "/home/pfremp/.virtualenvs/partfinder/local/lib/python2.7/site-packages/cities_light/management/commands/cities_light.py", line 129, in h
    andle
        geonames = Geonames(url, force=force)
      File "/home/pfremp/.virtualenvs/partfinder/local/lib/python2.7/site-packages/cities_light/geonames.py", line 30, in __init__
        self.downloaded = self.download(url, self.file_path, force)
      File "/home/pfremp/.virtualenvs/partfinder/local/lib/python2.7/site-packages/cities_light/geonames.py", line 48, in download
        remote_time = time.strptime(remote_file.headers['last-modified'],
      File "/usr/lib/python2.7/rfc822.py", line 388, in __getitem__
        return self.dict[name.lower()]
    KeyError: u'last-modified'

Any advice is appreciated.

**Comment by st4lk** [comment]
Hi, @pfremp 
Please tell, have you set any sources settings manually?
For example following:

    CITIES_LIGHT_COUNTRY_SOURCES
    CITIES_LIGHT_REGION_SOURCES
    CITIES_LIGHT_CITY_SOURCES
    CITIES_LIGHT_TRANSLATION_SOURCES
    CITIES_LIGHT_TRANSLATION_LANGUAGES

**Comment by pfremp** [comment]
Hi @st4lk 

These are the only settings that I have 

CITIES_LIGHT_TRANSLATION_LANGUAGES = ['en']
CITIES_LIGHT_INCLUDE_COUNTRIES = ['GB', 'FR']

SOUTH_MIGRATION_MODULES = {
    'cities_light': 'cities_light.south_migrations',
}

**Comment by pfremp** [comment]
I upgraded my hosting account and it is now working. I assume there were some restrictions on the basic account. 

Thanks!
